### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [eskilop/NorthernLightsVSC#1]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by spoenemann** [comment]
@eskilop could you look into this?

The latest published version is quite old:
https://open-vsx.org/extension/Eskilop/northernlights/1.0.1
That version did not include a license, which is another requirement set by the Eclipse Foundation. Republishing the extension with the included LICENSE file would fix the issue.

**Comment by brianking** [comment]
@eskilop Just a reminder for you in case you missed this. Our deadline was extended but the new one is approaching fast, this Friday January 29.

**Comment by eskilop** [comment]
Yup, sorry, I totally missed it. Thanks for the heads up, especially about the license. Anyway, I think i'll keep it de-listed, since I only have this extension for VS Code and don't plan publishing more anytime soon. Is there something more I've got to do to achieve this?

**Comment by spoenemann** [comment]
To achieve what? The extension is already delisted, there's nothing to do if you don't want to publish again.

**Comment by eskilop** [comment]
Alright then, thanks
